[workspace]
resolver = "2" 


members = [
    "jupiter-swap-api-client",
    "example",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-sdk = "2.2.0"
solana-client = "2.2.0"
solana-account-decoder = "2.2.0"
